### ISSUE TITLE
How can I get the pre macos 11 version?

### ISSUE THREAD

**Issue by Aahil52** [eclair4151/MC-Status-Widget-for-Minecraft#23]
I'm still on macOS Catalina since I haven't been bothered to update to Big Sur yet. Do you think I could get the previous version that doesn't require Big Sur?

**Comment by Aahil52** [comment]
Also just realized that you're the dev for push for apollo. Big fan of your tweaks!

**Comment by eclair4151** [comment]
Glad you enjoy! Unfortunately Apple only brought WidgetKit to Mac in Big Sur, so there is no way for me to release it for older macOS versions. Hope you understand

https://developer.apple.com/documentation/widgetkit/
