### ISSUE TITLE
MC Status Widget not Working

### ISSUE THREAD

**Issue by nicholasveronico** [eclair4151/MC-Status-Widget-for-Minecraft#25]
Hello.

I downloaded the MC Status app on my iPhone 12 Pro today and the widget doesn’t seem to work. I have the server added on the app; however, it doesn’t list it on the widget. Instead, it looks like the image attached. I restarted my phone multiple times and also waited hours and it still doesn’t seem to work.

Edit: I am on IOS 14.6
![D99986E8-7553-4C81-8D21-3F063B6A0F64](https://user-images.githubusercontent.com/80995156/125866805-9aedf6df-9c32-43fe-980d-103579e669fe.png)

**Comment by eclair4151** [comment]
It looks like you haven't selected a widget yet. Try long holding on the widget and pressing edit, then in the menu select which server to display. Let me know if that works

**Comment by nicholasveronico** [comment]
> It looks like you haven't selected a widget yet. Try long holding on the widget and pressing edit, then in the menu select which server to display. Let me know if that works

Yep that solved it. Thanks!
