### ISSUE TITLE
Add bedrock server support in app

### ISSUE THREAD

**Issue by EzraBrooks** [eclair4151/MC-Status-Widget-for-Minecraft#27]
I attempted to add my Bedrock server to the app, and it just shows as offline. Are Bedrock servers not supported, or did I misconfigure it?

**Comment by eclair4151** [comment]
Unfortunately bedrock is not supported.  (Mojang does not provide an API for bedrock as far as I can tell). Otherwise I would add support. 

Thanks for the note, I will add a message about that in the next update to clarify.

**Comment by eclair4151** [comment]
After some research I did find this. I think the player list may not be available but other info might. I'll look more into this in the future.

https://github.com/Werew1942/mcpe-status-api

**Comment by MannyGeosMeow** [comment]
This would be amazing, I have used your app for years now and it be awesome to finally get bedrock support! 😎

**Comment by eclair4151** [comment]
This feature is now finished and will be available in version 1.2 pending apple's approval in the net few days.

**Comment by EzraBrooks** [comment]
Works great! Thanks!
