### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by leanderkretschmer** [eclair4151/MC-Status-Widget-for-Minecraft#29]
A terminal for the server admins via ssh so you can shut down/restart/kick players and send commands in the server. Would be nice to have

**Comment by eclair4151** [comment]
Good idea, but this is pretty out of scope for this app, and there are many apps out there that already do this. (although many are paid and require separate software to install)
https://apps.apple.com/us/app/mcmyadmin-mobile-for-minecraft-server-admins/id469794253

Adding this to the feature request list, but It's pretty far down the list. I wouldn't expect updates anytime soon. Thanks for the support and trying out the app though!

**Comment by leanderkretschmer** [comment]
> Good idea, but this is pretty out of scope for this app, and there are many apps out there that already do this. (although many are paid and require separate software to install)
> 
> https://apps.apple.com/us/app/mcmyadmin-mobile-for-minecraft-server-admins/id469794253
> 
> 
> 
> Adding this to the feature request list, but It's pretty far down the list. I wouldn't expect updates anytime soon. Thanks for the support and trying out the app though!

I am using it actively
