### ISSUE TITLE
iCloud Syncing Support

### ISSUE THREAD

**Issue by AlexT1259** [eclair4151/MC-Status-Widget-for-Minecraft#30]
Me and my friends are hosting servers to play together on a home computer, the IP address changes about every week with home internet services, thus I have to update the server IP on the app frequently, but since there is no iCloud Syncing support, I have to update the server IP in the app on every devices I have, and this is quite annoying. 

Hope iCloud Syncing feature could be added for the app, and syncs all the server information across every devices with the same Apple ID and app installed.

**Comment by eclair4151** [comment]
Thanks for your feedback! This is on my list and hoping to get this out with the iOS 16 and lock screen update. I'll keep you updated.

**Comment by eclair4151** [comment]
Icloud sync is now supported and will be released with the iOS 17 rewrite in setpember
https://github.com/eclair4151/MC-Status-Widget-for-Minecraft/blob/a2849e8fae3fee87350d7215a467317025e4c520/MCStatus/Helpers/SwiftUIHelper.swift#L13

**Comment by eclair4151** [comment]
This is now complete. You can test the new 2.0 version of the app here on testflight before release:

WARNING!! There is currently a bug that means you will have to delete and re-add your widgets if you try out the new beta. This should be resolved before release but I didnt want to hold up testing.

https://testflight.apple.com/join/UqHNAYJn
