### ISSUE TITLE
Fetching incorrect port

### ISSUE THREAD

**Issue by BogTheMudWing** [eclair4151/MC-Status-Widget-for-Minecraft#31]
I have two Minecraft servers that run on the same network, but use two different ports. One uses the default 25565 while the other is 25566. Both widgets display the server on 25565. I know the servers are set up correctly and one is set to the port 25566 in the app, but it grabs the information of the other server.

**Comment by eclair4151** [comment]
If you don't mind can you email me your server address and I'll try to take a look. tomerjshemesh@gmail.com

**Comment by eclair4151** [comment]
I forget did we ever get this figured out, or does this need looking into?

**Comment by eclair4151** [comment]
👍
