### ISSUE TITLE
Add Server banners

### ISSUE THREAD

**Issue by strich3** [eclair4151/MC-Status-Widget-for-Minecraft#33]
From https://laby.net :)

**Comment by eclair4151** [comment]
There are not actually that many servers with non default banners on Laby 
https://github.com/LabyMod/server-media/tree/master/minecraft_servers

I am doing an update, which I plan to instead allow users to locally set their own banners pictures to the app, so they can get it from the laby github and set it, or find another/create thier own.

**Comment by strich3** [comment]
that‘s a good idea!

**Comment by strich3** [comment]
Also maybe get the icons from the laby github (If it exists) because most of them are optimized :)
