### ISSUE TITLE
Format MOTD

### ISSUE THREAD

**Issue by Stonley890** [eclair4151/MC-Status-Widget-for-Minecraft#34]
Apply formatting used in server MOTDs to be shown in the app rather than as plain text.

https://minecraft.fandom.com/wiki/Formatting_codes

**Comment by eclair4151** [comment]
This is now complete. You can test the new 2.0 version of the app here on testflight before release:

WARNING!! There is currently a bug that means you will have to delete and re-add your widgets if you try out the new beta. This should be resolved before release but I didnt want to hold up testing.

https://testflight.apple.com/join/UqHNAYJn
