### ISSUE TITLE
Monitoring bedrock server not possible on macOS

### ISSUE THREAD

**Issue by dmalorny** [eclair4151/MC-Status-Widget-for-Minecraft#38]
First of all: cool and useful App which runs on iOS and macOS!

But there seems to be a problem:

I have two minecraft servers running on the same host
- a bedrock server on port 19132
- a java server on port 25565

running the App on iOS, I can see both servers with its own specific version/motd

running the App on macOS only shows the java server even if I specify the correct ports
(it shows the version/motd/player count/etc. from the java-server even if I enter the bedrock port 19132 in the settings)

**Comment by eclair4151** [comment]
The new rewrite I am doing should fix this. I will let you know when it's ready to test.

**Comment by eclair4151** [comment]
This is now complete and can be tested with the new Testflight build
https://testflight.apple.com/join/UqHNAYJn
