### ISSUE TITLE
App wont sync with watch

### ISSUE THREAD

**Issue by zipCoder933** [eclair4151/MC-Status-Widget-for-Minecraft#44]
I have 2 servers on my watch app that I had on the iOS app before the new update.
Since then I have added other servers but the changes aren't being synced with the watch. 

I tried uninstalling and reinstalling the app, I tried syncing in the watch settings but nothing is working.

**Comment by eclair4151** [comment]
Unfortunately, iCloud has no way to 'force' a sync, but in my experience when it gets stuck like this when I restart the watch it seemed to fix it a lot of the time so give that a shot

**Comment by eclair4151** [comment]
@zipCoder933 did you get a chance to try restarting the watch and see if that fixed the problem?

**Comment by zipCoder933** [comment]
Yes. I uninstalled the app on my phone and watch and redownloaded it and its working now, luckily.
